### ISSUE TITLE
1.0.8 一直 系统接口404异常

### ISSUE THREAD

**Issue by uclort** [oddfar/campus-imaotai#118]
容器和镜像全部删掉重来也不行了，
docker-compose stop
docker-compose up -d 
相关命令重复执行多次，解决不了问题

**Comment by uclort** [comment]
campus-server 一开就 cpu 跑满，然后过一会就自动停止，下面是日志

```
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in com/oddfar/campus/framework/mapper/SysConfigMapper.java (best guess)
### The error may involve com.oddfar.campus.framework.mapper.SysConfigMapper.selectList
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[0;39m[33m2023-10-13 10:46:58[0;39m |[34mINFO [0;39m  |[34mDirectJDKLog.java:173[0;39m |[36mStopping service [Tomcat]
[0;39m[33m2023-10-13 10:46:58[0;39m |[1;31mERROR[0;39m  |[34mSpringApplication.java:870[0;39m |[36mApplication run failed
[0;39morg.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sysConfigController': Unsatisfied dependency expressed through field 'configService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysConfigServiceImpl': Invocation of init method failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in com/oddfar/campus/framework/mapper/SysConfigMapper.java (best guess)
### The error may involve com.oddfar.campus.framework.mapper.SysConfigMapper.selectList
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359)
	at com.oddfar.campus.CampusApplication.main(CampusApplication.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysConfigServiceImpl': Invocation of init method failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in com/oddfar/campus/framework/mapper/SysConfigMapper.java (best guess)
### The error may involve com.oddfar.campus.framework.mapper.SysConfigMapper.selectList
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
	... 28 common frames omitted
Caused by: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in com/oddfar/campus/framework/mapper/SysConfigMapper.java (best guess)
### The error may involve com.oddfar.campus.framework.mapper.SysConfigMapper.selectList
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy116.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy137.selectList(Unknown Source)
	at com.oddfar.campus.common.core.BaseMapperX.selectList(BaseMapperX.java:71)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$DefaultMethodInvoker.invoke(MybatisMapperProxy.java:162)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy137.selectList(Unknown Source)
	at com.oddfar.campus.framework.service.impl.SysConfigServiceImpl.loadingConfigCache(SysConfigServiceImpl.java:143)
	at com.oddfar.campus.framework.service.impl.SysConfigServiceImpl.init(SysConfigServiceImpl.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 40 common frames omitted
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in com/oddfar/campus/framework/mapper/SysConfigMapper.java (best guess)
### The error may involve com.oddfar.campus.framework.mapper.SysConfigMapper.selectList
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:153)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 61 common frames omitted
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:81)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy141.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	... 68 common frames omitted
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 80 common frames omitted
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
	... 93 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 96 common frames omitted
```

**Comment by uclort** [comment]
降回 1.0.7，已正常。

**Comment by CNJiaxuanChen** [comment]
同样情况，108campus-server起不来 看日志似乎和无法连接数据库有关 并且测试campus-redis手动结束后再启动也起不来，降回107正常

**Comment by oddfar** [comment]
打包的时候我选择错环境了，选的 dev 环境，所以docker里数据库 redis 连不上
等晚点我重新打包下

**Comment by oddfar** [comment]
1.0.8已重新部署

**Comment by Adangs** [comment]
<img width="569" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/5443355/392a8e84-015a-43ab-a40f-3aec0dd9c1ea">

刚下载的还是404

**Comment by Adangs** [comment]
> 打包的时候我选择错环境了，选的 dev 环境，所以docker里数据库 redis 连不上 等晚点我重新打包下

<img width="540" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/5443355/325c096c-cbe6-46f0-9ef3-8aa26c7652e3">

就换了个端口别的没改，还是404

**Comment by oddfar** [comment]
> > 打包的时候我选择错环境了，选的 dev 环境，所以docker里数据库 redis 连不上 等晚点我重新打包下
> 
> <img alt="image" width="540" src="https://user-images.githubusercontent.com/5443355/274828750-325c096c-cbe6-46f0-9ef3-8aa26c7652e3.png">
> 就换了个端口别的没改，还是404

看看campus-service容器启动了吗，后端服务换端口了，nginx需要修改下
`nginx.conf` 文件里的 `location /prod-api/{` 里的 `proxy_pass` 端口修改成更改后的

**Comment by 461993097** [comment]
> > > 打包的时候我选择错环境了，选的 dev 环境，所以docker里数据库 redis 连不上 等晚点我重新打包下
> > 
> > 
> > <img alt="image" width="540" src="https://user-images.githubusercontent.com/5443355/274828750-325c096c-cbe6-46f0-9ef3-8aa26c7652e3.png">
> > 就换了个端口别的没改，还是404
> 
> 看看campus-service容器启动了吗，后端服务换端口了，nginx需要修改下 `nginx.conf` 文件里的 `location /prod-api/{` 里的 `proxy_pass` 端口修改成更改后的

我也是同样的问题，端口是默认的，campus-service启动马上就会退出，日志中最上边的报错为“ERROR  |HikariPool.java:594 |HikariPool-1 - Exception during pool initialization.”

**Comment by uclort** [comment]
我是直接全部删掉重新部署的，现在正常运行了一天，建议你们也从头来。😂

**Comment by Adangs** [comment]
> docker-compose stop

<img width="1455" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/5443355/4add3fdb-54ce-47c2-a471-2992b6fdf010">

<img width="730" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/5443355/4c7bf65a-e6b9-4dc7-ac21-9db9ba1ec258">


需要怎么调整呢

**Comment by Adangs** [comment]
<img width="1656" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/5443355/b145b75e-e4a3-4ed7-80be-0a3f60106e69">

**Comment by oddfar** [comment]
> <img alt="image" width="1656" src="https://user-images.githubusercontent.com/5443355/275368832-b145b75e-e4a3-4ed7-80be-0a3f60106e69.png">

报错内容显示的表不存在，表没导入好

**Comment by Manchuker1120** [comment]
> > > > 打包的时候我选择错环境了，选的 dev 环境，所以docker里数据库 redis 连不上 等晚点我重新打包下
> > > 
> > > 
> > > <img alt="image" width="540" src="https://user-images.githubusercontent.com/5443355/274828750-325c096c-cbe6-46f0-9ef3-8aa26c7652e3.png">
> > > 就换了个端口别的没改，还是404
> > 
> > 
> > 看看campus-service容器启动了吗，后端服务换端口了，nginx需要修改下 `nginx.conf` 文件里的 `location /prod-api/{` 里的 `proxy_pass` 端口修改成更改后的
> 
> 我也是同样的问题，端口是默认的，campus-service启动马上就会退出，日志中最上边的报错为“ERROR |HikariPool.java:594 |HikariPool-1 - Exception during pool initialization.”

一样，现在能重新下载包了吗？我刚刚试了，还是一样。

**Comment by Manchuker1120** [comment]
找到原因了，只需要去mysql 把sql注入就好了。因为容器创建启动的时候，sql没有注入成功。

**Comment by sunzongzheng** [comment]
> 找到原因了，只需要去mysql 把sql注入就好了。因为容器创建启动的时候，sql没有注入成功。

同使用这个方式解决了。
1. `docker ps -a`找到mysql的容器id
2. `docker cp ./db/campus_imaotai-V1.0.5.sql {mysql的容器id}:/`将sql文件复制到mysql容器内
3. `docker exec -it {mysql的容器id} bash`进入容器
4. `mysql -u root -p`并输入密码`oddfar_imaotai`回车，进入mysql程序
5. `use campus_imaotai;`选择数据库
6. `source /campus_imaotai-V1.0.5.sql`执行sql，成功后`exit;`退出mysql，并`exit`退出容器
7. `docker-compose restart`，重启所有容器，稍等1分钟，再访问页面应该就行了

**Comment by Jameslai93** [comment]
同样问题，烦哦

**Comment by Weltolk** [comment]
> > 找到原因了，只需要去mysql 把sql注入就好了。因为容器创建启动的时候，sql没有注入成功。
> 
> 同使用这个方式解决了。
> 
> 1. `docker ps -a`找到mysql的容器id
> 2. `docker cp ./db/campus_imaotai-V1.0.5.sql {mysql的容器id}:/`将sql文件复制到mysql容器内
> 3. `docker exec -it {mysql的容器id} bash`进入容器
> 4. `mysql -u root -p`并输入密码`oddfar_imaotai`回车，进入mysql程序
> 5. `use campus_imaotai;`选择数据库
> 6. `source /campus_imaotai-V1.0.5.sql`执行sql，成功后`exit;`退出mysql，并`exit`退出容器
> 7. `docker-compose restart`，重启所有容器，稍等1分钟，再访问页面应该就行了

sql导入了,4个镜像都启动了,还是404,日志没有报错

**Comment by wx13069** [comment]
每次启动容器都要手动注入SQL文件，怎么解决这个问题

**Comment by big-kota** [comment]
> > > 找到原因了，只需要去mysql 把sql注入就好了。因为容器创建启动的时候，sql没有注入成功。
> > 
> > 
> > 同使用这个方式解决了。
> > 
> > 1. `docker ps -a`找到mysql的容器id
> > 2. `docker cp ./db/campus_imaotai-V1.0.5.sql {mysql的容器id}:/`将sql文件复制到mysql容器内
> > 3. `docker exec -it {mysql的容器id} bash`进入容器
> > 4. `mysql -u root -p`并输入密码`oddfar_imaotai`回车，进入mysql程序
> > 5. `use campus_imaotai;`选择数据库
> > 6. `source /campus_imaotai-V1.0.5.sql`执行sql，成功后`exit;`退出mysql，并`exit`退出容器
> > 7. `docker-compose restart`，重启所有容器，稍等1分钟，再访问页面应该就行了
> 
> sql导入了,4个镜像都启动了,还是404,日志没有报错

谢谢，遇到同样的问题了，按照这个方法解决了
还需要在 jdbc 的配置中把 useSSL 配置为 false

**Comment by didiplus** [comment]
我再本地部署时候，数据库调试没有问题的。启动项目提示数据库链接失败
`Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'imaotai'@'112.97.46.132' (using password: YES)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:128)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:849)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:771)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:739)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:156)`

112.97.46.132 这个地址不知道的。我的项目中两个配置文件都没有设置这个地址，都是用的本地的数据库
