### ISSUE TITLE
linux campus-server一直起不来

### ISSUE THREAD

**Issue by binz123** [oddfar/campus-imaotai#135]
问题：其他服务都起来了，就campus-server的服务起不来，链接不上数据库

`campus-server    | 	... 80 common frames omitted
campus-server    | 2023-11-14 21:19:03 |ERROR  |HikariPool.java:594 |HikariPool-1 - Exception during pool initialization.
campus-server    | java.sql.SQLException: null,  message from server: "Host '172.18.0.4' is not allowed to connect to this MySQL server"
campus-server    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
campus-server    | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
campus-server    | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
campus-server    | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
campus-server    | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
campus-server    | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
campus-server    | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
campus-server    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
campus-server    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
campus-server    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
campus-server    | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
campus-server    | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
campus-server    | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
campus-server    | 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
campus-server    | 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
campus-server    | 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
campus-server    | 	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
campus-server    | 	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
campus-server    | 	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
campus-server    | 	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
campus-server    | 	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
campus-server    | 	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
campus-server    | 	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
campus-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
campus-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
campus-server    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
campus-server    | 	at java.lang.reflect.Method.invoke(Method.java:498)
campus-server    | 	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
campus-server    | 	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
campus-server    | 	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
campus-server    | 	at com.sun.proxy.$Proxy141.update(Unknown Source)
campus-server    | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
campus-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
campus-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
campus-server    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
campus-server    | 	at java.lang.reflect.Method.invoke(Method.java:498)
campus-server    | 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
campus-server    | 	at com.sun.proxy.$Proxy116.update(Unknown Source)
campus-server    | 	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:288)
campus-server    | 	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:64)
campus-server    | 	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
campus-server    | 	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
campus-server    | 	at com.sun.proxy.$Proxy122.truncateShop(Unknown Source)
campus-server    | 	at com.oddfar.campus.business.service.impl.IShopServiceImpl.refreshShop(IShopServiceImpl.java:76)
campus-server    | 	at com.oddfar.campus.business.service.impl.IShopServiceImpl$$FastClassBySpringCGLIB$$5cecaa53.invoke(<generated>)
campus-server    | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
campus-server    | 	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
campus-server    | 	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
campus-server    | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
campus-server    | 	at com.oddfar.campus.business.service.impl.IShopServiceImpl$$EnhancerBySpringCGLIB$$9ccd3a8c.refreshShop(<generated>)
campus-server    | 	at com.oddfar.campus.business.service.impl.IMTServiceImpl.refreshAll(IMTServiceImpl.java:487)
campus-server    | 	at com.oddfar.campus.business.service.impl.IMTServiceImpl$1.run(IMTServiceImpl.java:72)
campus-server    | 	at java.lang.Thread.run(Thread.java:750)
campus-server    | Exception in thread "Thread-2" org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
campus-server    | ### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: null,  message from server: "Host '172.18.0.4' is not allowed to connect to this MySQL server"
campus-server    | ### The error may exist in com/oddfar/campus/business/mapper/IShopMapper.java (best guess)
campus-server    | ### The error may involve com.oddfar.campus.business.mapper.IShopMapper.truncateShop
campus-server    | ### The error occurred while executing an update
campus-server    | ### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: null,  message from server: "Host '172.18.0.4' is not allowed to connect to this MySQL server"
campus-server    | 	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
campus-server    | 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
campus-server    | 	at com.sun.proxy.$Proxy116.update(Unknown Source)
campus-server    | 	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:288)
campus-server    | 	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:64)
campus-server    | 	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
campus-server    | 	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
campus-server    | 	at com.sun.proxy.$Proxy122.truncateShop(Unknown Source)
campus-server    | 	at com.oddfar.campus.business.service.impl.IShopServiceImpl.refreshShop(IShopServiceImpl.java:76)
campus-server    | 	at com.oddfar.campus.business.service.impl.IShopServiceImpl$$FastClassBySpringCGLIB$$5cecaa53.invoke(<generated>)
campus-server    | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
campus-server    | 	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
campus-server    | 	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
campus-server    | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
campus-server    | 	at com.oddfar.campus.business.service.impl.IShopServiceImpl$$EnhancerBySpringCGLIB$$9ccd3a8c.refreshShop(<generated>)
campus-server    | 	at com.oddfar.campus.business.service.impl.IMTServiceImpl.refreshAll(IMTServiceImpl.java:487)
campus-server    | 	at com.oddfar.campus.business.service.impl.IMTServiceImpl$1.run(IMTServiceImpl.java:72)
campus-server    | 	at java.lang.Thread.run(Thread.java:750)
campus-server    | Caused by: org.apache.ibatis.exceptions.PersistenceException:
campus-server    | ### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: null,  message from server: "Host '172.18.0.4' is not allowed to connect to this MySQL server"
campus-server    | ### The error may exist in com/oddfar/campus/business/mapper/IShopMapper.java (best guess)
campus-server    | ### The error may involve com.oddfar.campus.business.mapper.IShopMapper.truncateShop
campus-server    | ### The error occurred while executing an update
campus-server    | ### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: null,  message from server: "Host '172.18.0.4' is not allowed to connect to this MySQL server"
campus-server    | 	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
campus-server    | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196)
campus-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
campus-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
campus-server    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
campus-server    | 	at java.lang.reflect.Method.invoke(Method.java:498)
campus-server    | 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
campus-server    | 	... 16 more
campus-server    | Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: null,  message from server: "Host '172.18.0.4' is not allowed to connect to this MySQL server"
campus-server    | 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
campus-server    | 	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
campus-server    | 	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
campus-server    | 	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
campus-server    | 	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
campus-server    | 	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
campus-server    | 	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
campus-server    | 	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
campus-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
campus-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
campus-server    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
campus-server    | 	at java.lang.reflect.Method.invoke(Method.java:498)
campus-server    | 	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
campus-server    | 	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
campus-server    | 	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
campus-server    | 	at com.sun.proxy.$Proxy141.update(Unknown Source)
campus-server    | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
campus-server    | 	... 21 more
campus-server    | Caused by: java.sql.SQLException: null,  message from server: "Host '172.18.0.4' is not allowed to connect to this MySQL server"
campus-server    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
campus-server    | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
campus-server    | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
campus-server    | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
campus-server    | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
campus-server    | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
campus-server    | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
campus-server    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
campus-server    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
campus-server    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
campus-server    | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
campus-server    | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
campus-server    | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
campus-server    | 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
campus-server    | 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
campus-server    | 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
campus-server    | 	... 37 more
campus-server exited with code 1`

**Comment by eugene91cn** [comment]
后来解决了吗

**Comment by ruixule** [comment]
我的也是这个错误 你后来 有解决了么
