### ISSUE TITLE
[bug]: 验证码发送失败

### ISSUE THREAD

**Issue by codesdevs** [oddfar/campus-imaotai#192]
## 版本情况

campus框架版本： 1.0.11

本项目campus-imaotai版本： 1.0.11

## 问题描述

今天没有执行预约，手动预约失败，发送验证码也没成功

1. 使用的什么功能
预约，验证码发送
2. 复现代码（如有）

3. 测试涉及到的文件（如有）

## 问题内容（如有）

执行报错--[预约项目]：10941
[结果返回]：查询所在省市的投放产品和数量error: %s

送验证码错误
com.oddfar.campus.common.exception.ServiceException: 发送验证码错误
        at com.oddfar.campus.business.service.impl.IMTServiceImpl.sendCode(IMTServiceImpl.java:131)
        at com.oddfar.campus.business.service.impl.IMTServiceImpl$$FastClassBySpringCGLIB$$fb9c8022.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at com.oddfar.campus.business.service.impl.IMTServiceImpl$$EnhancerBySpringCGLIB$$262302fd.sendCode(<generated>)
        at com.oddfar.campus.business.controller.IUserController.sendCode(IUserController.java:54)
        at com.oddfar.campus.business.controller.IUserController$$FastClassBySpringCGLIB$$49068076.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

**Comment by SamSunChan** [comment]
添加账户的时候，发送验证码错误
2024-01-11 16:35:26 |INFO   |IMTServiceImpl.java:126 |「发送验证码返回」：{"code":4010,"message":"获取验证码失败"}
2024-01-11 16:35:26 |ERROR  |IMTServiceImpl.java:130 |「发送验证码-失败」：{"code":4010,"message":"获取验证码失败"}
2024-01-11 16:35:26 |ERROR  |GlobalExceptionHandler.java:53 |发送验证码错误
com.oddfar.campus.common.exception.ServiceException: 发送验证码错误
	at com.oddfar.campus.business.service.impl.IMTServiceImpl.sendCode(IMTServiceImpl.java:131)
	at com.oddfar.campus.business.service.impl.IMTServiceImpl$$FastClassBySpringCGLIB$$fb9c8022.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at com.oddfar.campus.business.service.impl.IMTServiceImpl$$EnhancerBySpringCGLIB$$d1c537d0.sendCode(<generated>)
	at com.oddfar.campus.business.controller.IUserController.sendCode(IUserController.java:54)
	at com.oddfar.campus.business.controller.IUserController$$FastClassBySpringCGLIB$$49068076.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)

**Comment by Ouyuone** [comment]
我也是这样的 why？

**Comment by xiankaiyao** [comment]
我也是

**Comment by xiankaiyao** [comment]
重启[campus-server]后就可以了，什么鬼

**Comment by alan032** [comment]
新增用户，发送验证码失败

**Comment by alan032** [comment]
> 添加账户的时候，发送验证码错误 2024-01-11 16:35:26 |INFO |IMTServiceImpl.java:126 |「发送验证码返回」：{"code":4010,"message":"获取验证码失败"} 2024-01-11 16:35:26 |ERROR |IMTServiceImpl.java:130 |「发送验证码-失败」：{"code":4010,"message":"获取验证码失败"} 2024-01-11 16:35:26 |ERROR |GlobalExceptionHandler.java:53 |发送验证码错误 com.oddfar.campus.common.exception.ServiceException: 发送验证码错误 at com.oddfar.campus.business.service.impl.IMTServiceImpl.sendCode(IMTServiceImpl.java:131) at com.oddfar.campus.business.service.impl.IMTServiceImpl$$FastClassBySpringCGLIB$$fb9c8022.invoke() at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) at com.oddfar.campus.business.service.impl.IMTServiceImpl$$EnhancerBySpringCGLIB$$d1c537d0.sendCode() at com.oddfar.campus.business.controller.IUserController.sendCode(IUserController.java:54) at com.oddfar.campus.business.controller.IUserController$$FastClassBySpringCGLIB$$49068076.invoke() at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)

解决了吗？我一样的问题。。。

**Comment by hohoho666** [comment]
参考这个 https://github.com/oddfar/campus-imaotai/issues/46

**Comment by SamSunChan** [comment]
已解决：代码问题，我自己修改重新编译的jar包就没问题了，我在armv7，arm64，amd64部署都遇到这个问题。主要是短信sendCode函数里时间戳没统一导致，导致时差，所以发送验证码失败。稍微改下即可

**Comment by oddfar** [comment]
可以参考：https://github.com/oddfar/campus-imaotai/issues/220
