### ISSUE TITLE
最新V1.0.12版本docker一键安装文件

### ISSUE THREAD

**Issue by xiankaiyao** [oddfar/campus-imaotai#250]
按照大佬教程打包了最新的一键安装包，有需要的同学可以去下载。我自己把端口改成了11080，其他都没变。
https://github.com/xiankaiyao/campus-imaotai/releases/tag/v1.0.12

**Comment by dream-coffee** [comment]
大佬 部署完成后 访问系统  没办法刷新验证码 显示404报错 请问是什么原因呢

**Comment by xiankaiyao** [comment]
> 大佬 部署完成后 访问系统 没办法刷新验证码 显示404报错 请问是什么原因呢
docker ps看看容器都起来了吗，server那个没起来会报错

**Comment by thodison** [comment]
部署时出现错误：
Error response from daemon: Bind mount failed: '/volume1/docker/campus-imt/redis/data' does not exists

**Comment by xiankaiyao** [comment]
> '/volume1/docker/campus-imt/redis/data

错误提示是：   /volume1/docker/campus-imt/redis/data目录不存在。
创建该文件夹后再试试     mkdir -p /volume1/docker/campus-imt/redis/data

**Comment by juzi0331** [comment]
> 大佬 部署完成后 访问系统 没办法刷新验证码 显示404报错 请问是什么原因呢

修改docker-compose.yml文件sql数据库版本为:
mysql:8.0.35
redis:6.2.12
我用原作者的版本运行也报错404,更换了版本就可以了

**Comment by juzi0331** [comment]
> > 大佬 部署完成后 访问系统 没办法刷新验证码 显示404报错 请问是什么原因呢
> > docker ps看看容器都起来了吗，server那个没起来会报错

我用这个大佬的也是,更换了数据库和redis版本就可以了.
https://github.com/juzi0331/campus-imaotai/releases/tag/v1.0.12
我自己构建的只替换了版本,可以正常运行
![微信截图_20240206183447](https://github.com/oddfar/campus-imaotai/assets/154888639/96cf7c5c-ce3c-4b18-a265-557e93425dd6)

**Comment by luoxufeiyan** [comment]
同无法加载验证码，容器状态正常，应该是数据库表没有导入成功。

下面是 campus-server 的 log，与 https://github.com/oddfar/campus-imaotai/issues/75 问题一致。

<details><summary>Details</summary>
<p>


  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.5.15)

2024-02-15 14:20:36 |INFO   |Version.java:21 |HV000001: Hibernate Validator 6.2.5.Final
2024-02-15 14:20:36 |INFO   |StartupInfoLogger.java:55 |Starting CampusApplication using Java 1.8.0_402 on b0744afe5650 with PID 1 (/home/campus/campus.jar started by root in /home/campus)
2024-02-15 14:20:36 |DEBUG  |StartupInfoLogger.java:56 |Running with Spring Boot v2.5.15, Spring v5.3.27
2024-02-15 14:20:36 |INFO   |SpringApplication.java:686 |The following 1 profile is active: "prod"
2024-02-15 14:21:01 |INFO   |DirectJDKLog.java:173 |Initializing ProtocolHandler ["http-nio-8160"]
2024-02-15 14:21:02 |INFO   |DirectJDKLog.java:173 |Starting service [Tomcat]
2024-02-15 14:21:02 |INFO   |DirectJDKLog.java:173 |Starting Servlet engine: [Apache Tomcat/9.0.75]
2024-02-15 14:21:03 |INFO   |DirectJDKLog.java:173 |Initializing Spring embedded WebApplicationContext
2024-02-15 14:21:09 |DEBUG  |GenericFilterBean.java:242 |Filter 'jwtAuthenticationTokenFilter' configured for use
2024-02-15 14:21:11 |INFO   |HikariDataSource.java:80 |master - Starting...
2024-02-15 14:21:17 |INFO   |HikariDataSource.java:82 |master - Start completed.
2024-02-15 14:21:17 |INFO   |DynamicRoutingDataSource.java:160 |dynamic-datasource - add a datasource named [master] success
2024-02-15 14:21:17 |INFO   |DynamicRoutingDataSource.java:243 |dynamic-datasource initial loaded [1] datasource,primary datasource named [master]
 _ _   |_  _ _|_. ___ _ |    _
| | |\/|_)(_| | |_\  |_)||_|_\
     /               |
                        3.5.4.1
2024-02-15 14:21:38 |WARN   |AbstractApplicationContext.java:591 |Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with n
ame 'sysConfigController': Unsatisfied dependency expressed through field 'configService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysConfigServiceImpl': Invocation of init method failed; nested exception is org.springframework.jdbc.BadSqlGrammarException:
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
### The error may exist in com/oddfar/campus/framework/mapper/SysConfigMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  config_id,config_name,config_key,config_value,config_type,group_code,remark,create_time,create_user,update_time,update_user,del_flag  FROM sys_config  WHERE del_flag=0
### Cause: java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
2024-02-15 14:21:38 |INFO   |DynamicRoutingDataSource.java:217 |dynamic-datasource start closing ....
2024-02-15 14:21:38 |INFO   |HikariDataSource.java:350 |master - Shutdown initiated...
2024-02-15 14:21:39 |INFO   |HikariDataSource.java:352 |master - Shutdown completed.
2024-02-15 14:21:39 |INFO   |DefaultDataSourceDestroyer.java:98 |dynamic-datasource close the datasource named [master] success,
2024-02-15 14:21:39 |INFO   |DynamicRoutingDataSource.java:221 |dynamic-datasource all closed success,bye
2024-02-15 14:21:39 |INFO   |DirectJDKLog.java:173 |Stopping service [Tomcat]
2024-02-15 14:21:44 |ERROR  |SpringApplication.java:870 |Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sysConfigController': Unsatisfied dependency expressed through field 'configService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysConfigServiceImpl': Invocation of init method failed; nested exception is org.springframework.jdbc.BadSqlGrammarException:
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
### The error may exist in com/oddfar/campus/framework/mapper/SysConfigMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  config_id,config_name,config_key,config_value,config_type,group_code,remark,create_time,create_user,update_time,update_user,del_flag  FROM sys_config  WHERE del_flag=0
### Cause: java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:343)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359)
        at com.oddfar.campus.CampusApplication.main(CampusApplication.java:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysConfigServiceImpl': Invocation of init method failed; nested exception is org.springframework.jdbc.BadSqlGrammarException:
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
### The error may exist in com/oddfar/campus/framework/mapper/SysConfigMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  config_id,config_name,config_key,config_value,config_type,group_code,remark,create_time,create_user,update_time,update_user,del_flag  FROM sys_config  WHERE del_flag=0
### Cause: java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
        ... 28 common frames omitted
Caused by: org.springframework.jdbc.BadSqlGrammarException:
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
### The error may exist in com/oddfar/campus/framework/mapper/SysConfigMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  config_id,config_name,config_key,config_value,config_type,group_code,remark,create_time,create_user,update_time,update_user,del_flag  FROM sys_config  WHERE del_flag=0
### Cause: java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
        at com.sun.proxy.$Proxy115.selectList(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:166)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:152)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
        at com.sun.proxy.$Proxy154.selectList(Unknown Source)
        at com.oddfar.campus.common.core.BaseMapperX.selectList(BaseMapperX.java:59)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$DefaultMethodInvoker.invoke(MybatisMapperProxy.java:166)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
        at com.sun.proxy.$Proxy154.selectList(Unknown Source)
        at com.oddfar.campus.framework.service.impl.SysConfigServiceImpl.loadingConfigCache(SysConfigServiceImpl.java:144)
        at com.oddfar.campus.framework.service.impl.SysConfigServiceImpl.init(SysConfigServiceImpl.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        ... 40 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Table 'campus_imaotai.sys_config' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at com.sun.proxy.$Proxy160.query(Unknown Source)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:65)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:333)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:158)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:110)
        at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:81)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
        at com.sun.proxy.$Proxy157.query(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:142)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
        ... 61 common frames omitted


</p>
</details>

**Comment by yaolee** [comment]
感谢，一次成功了

**Comment by xianglongwei** [comment]
成功，谢大佬

**Comment by yaolee** [comment]
> 成功，谢大佬

安装这个，怎么再把作者校园加入，有一点不会。第一次接触这个CAMOUS

**Comment by Clove-MJC** [comment]
[+] Building 0.5s (2/2) FINISHED                                                                                           
 => [internal] load build definition from redis-dockerfile                                                            0.0s
 => => transferring dockerfile: 323B                                                                                  0.0s
 => ERROR [internal] load metadata for docker.io/library/redis:latest

**Comment by 125540947** [comment]
用户密码是什么

**Comment by Rolanddaan** [comment]
> > 大佬 部署完成后 访问系统 没办法刷新验证码 显示404报错 请问是什么原因呢
> 
> docker ps看看容器都起来了吗，server那个没起来会报错
> 
> 

咱们两个一样的问题，有好多文件夹都得从新建立，也不知道对不对，后台能进去，但是报错404并且没有验证码，然后server起不来

**Comment by xiankaiyao** [comment]
> > > 大佬 部署完成后 访问系统 没办法刷新验证码 显示404报错 请问是什么原因呢
> > 
> > 
> > docker ps看看容器都起来了吗，server那个没起来会报错
> 
> 咱们两个一样的问题，有好多文件夹都得从新建立，也不知道对不对，后台能进去，但是报错404并且没有验证码，然后server起不来

你先把其他服务起来，在重启server就可以了

**Comment by xiankaiyao** [comment]
> 用户密码是什么

网站账号
管理员

admin admin123

普通用户（啥也干不了）

zhiyuan 123456

测试用户（可添加i茅台）

test 123456

**Comment by q99266** [comment]
|ERROR  |GlobalExceptionHandler.java:64 |请求地址'/captchaImage',发生未知异常.
java.lang.NullPointerException: null
