### ISSUE TITLE
com.oddfar.campus.common.exception.ServiceException: 发送验证码错误 	at com.oddfar.campus.business.service.impl.Testdemo.sendCode(Testdemo.java:90) 	at com.oddfar.campus.business.service.impl.Testdemo.main(Testdemo.java:41)

### ISSUE THREAD

**Issue by lizhichao999** [oddfar/campus-imaotai#357]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### campus框架版本

1.0.11

### 本项目 campus-imaotai 版本

1.0.11

### 运行环境

Windows (64)

### 运行架构

x86

### 问题描述

com.oddfar.campus.common.exception.ServiceException: 发送验证码错误 	at com.oddfar.campus.business.service.impl.Testdemo.sendCode(Testdemo.java:90) 	at com.oddfar.campus.business.service.impl.Testdemo.main(Testdemo.java:41)
调发送验证码的端口返回信息
{"code":4010,"message":"获取验证码失败"}
页面添加账号报发送验证码错误

### 期望的结果是什么？

正常发送验证码

### 日志记录（可选）

024-04-26 07:58:14 2024-04-26 07:58:14 |INFO   |IMTServiceImpl.java:126 |「发送验证码返回」：{"code":4010,"message":"获取验证码失败"}
2024-04-26 07:58:14 2024-04-26 07:58:14 |ERROR  |IMTServiceImpl.java:130 |「发送验证码-失败」：{"code":4010,"message":"获取验证码失败"}
2024-04-26 07:58:14 2024-04-26 07:58:14 |ERROR  |GlobalExceptionHandler.java:53 |发送验证码错误
2024-04-26 07:58:14 com.oddfar.campus.common.exception.ServiceException: 发送验证码错误
2024-04-26 07:58:14     at com.oddfar.campus.business.service.impl.IMTServiceImpl.sendCode(IMTServiceImpl.java:131)
2024-04-26 07:58:14     at com.oddfar.campus.business.service.impl.IMTServiceImpl$$FastClassBySpringCGLIB$$fb9c8022.invoke(<generated>)
2024-04-26 07:58:14     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
2024-04-26 07:58:14     at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
2024-04-26 07:58:14     at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
2024-04-26 07:58:14     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
2024-04-26 07:58:14     at com.oddfar.campus.business.service.impl.IMTServiceImpl$$EnhancerBySpringCGLIB$$2327dd37.sendCode(<generated>)
2024-04-26 07:58:14     at com.oddfar.campus.business.controller.IUserController.sendCode(IUserController.java:54)
2024-04-26 07:58:14     at com.oddfar.campus.business.controller.IUserController$$FastClassBySpringCGLIB$$49068076.invoke(<generated>)
2024-04-26 07:58:14     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
2024-04-26 07:58:14     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
2024-04-26 07:58:14     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2024-04-26 07:58:14     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
2024-04-26 07:58:14     at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
2024-04-26 07:58:14     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
2024-04-26 07:58:14     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
2024-04-26 07:58:14     at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
2024-04-26 07:58:14     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
2024-04-26 07:58:14     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
2024-04-26 07:58:14     at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
2024-04-26 07:58:14     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
2024-04-26 07:58:14     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)

**Comment by oddfar** [comment]
用最新版 v1.0.13 试试
