### ISSUE TITLE
新版本内存占比降低很多！好评！

### ISSUE THREAD

**Issue by SWPUDails** [oddfar/campus-imaotai#381]
## 例行检查

+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**Comment by SWPUDails** [comment]
嗯呢。1.0.13版本，我2G的内存，之前内存使用占比80%，更新了以后内存占比60%出头。

**Comment by uxhao-o** [comment]
使用轻量版本docker启动。只能预约一次，第三天docker容器好像就崩掉了。查看了下日志感觉有些奇怪。

以下是每天18点以后查询申购结果的报错信息：

```bash

org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such function: RAND)
### The error may exist in com/oddfar/campus/business/mapper/IUserMapper.java (best guess)
### The error may involve com.oddfar.campus.business.mapper.IUserMapper.updateUserMinuteBatch
### The error occurred while executing an update
### SQL: UPDATE i_user SET `minute` = (SELECT FLOOR(RAND() * 50 + 1)) WHERE random_minute = "0"
### Cause: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such function: RAND)
; uncategorized SQLException; SQL state [null]; error code [1]; [SQLITE_ERROR] SQL error or missing database (no such function: RAND); nested exception is org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such function: RAND)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:93)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
	at com.sun.proxy.$Proxy114.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:288)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:64)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:152)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy126.updateUserMinuteBatch(Unknown Source)
	at com.oddfar.campus.business.service.impl.IUserServiceImpl.updateUserMinuteBatch(IUserServiceImpl.java:98)
	at com.oddfar.campus.business.service.impl.IUserServiceImpl$$FastClassBySpringCGLIB$$8370325e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such function: RAND)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.throwex(DB.java:1150)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:206)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at com.p6spy.engine.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:118)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:90)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:60)
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at com.sun.proxy.$Proxy139.prepare(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:90)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at com.sun.proxy.$Proxy138.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	... 19 more
[33m2025-03-23 01:10:00[0;39m |[31mWARN [0;39m  |[34mAsyncExecutionAspectSupport.java:319[0;39m |[36mException handler for async method 'public void com.oddfar.campus.business.service.impl.IUserServiceImpl.updateUserMinuteBatch()' threw unexpected exception itself
[0;39mcom.oddfar.campus.common.exception.ServiceException: Exception message - 
### Error updating database.  Cause: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such function: RAND)
### The error may exist in com/oddfar/campus/business/mapper/IUserMapper.java (best guess)
### The error may involve com.oddfar.campus.business.mapper.IUserMapper.updateUserMinuteBatch
### The error occurred while executing an update
### SQL: UPDATE i_user SET `minute` = (SELECT FLOOR(RAND() * 50 + 1)) WHERE random_minute = "0"
### Cause: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such function: RAND)
; uncategorized SQLException; SQL state [null]; error code [1]; [SQLITE_ERROR] SQL error or missing database (no such function: RAND); nested exception is org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such function: RAND), Method name - updateUserMinuteBatch
	at com.oddfar.campus.framework.config.AsyncConfig.lambda$getAsyncUncaughtExceptionHandler$0(AsyncConfig.java:44)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.handleError(AsyncExecutionAspectSupport.java:316)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:124)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```


以下sql是预约成功以后执行的，该条命令从预约成功开始 要执行160次，即预约成功以后每分钟执行一次，执行120分钟。sql语句中的minute = 0 开始到minute = 59 反复执行两轮。执行完两轮以后第二天docker容器就崩掉了，不自动预约了，需要重新启动才能续命一天。然后又崩掉。

```bash
 Consume Time：5 ms 2025-03-23 09:02:00
 Execute SQL：SELECT mobile,user_id,token,cookie,device_id,item_code,ishop_id,province_name,city_name,address,lat,lng,minute,random_minute,shop_type,push_plus_token,json_result,remark,expire_time,create_time,create_user,update_time,update_user,del_flag FROM i_user WHERE del_flag=0 AND (minute = 2 AND lat <> '' AND lng <> '' AND item_code <> '' AND item_code IS NOT NULL)
```

**Comment by gemail1024** [comment]
[SQLITE_ERROR] SQL error or missing database (no such function: RAND)已修复，近期我更新一下sqlite镜像 @uxhao-o
