### ISSUE TITLE
发送验证码错误

### ISSUE THREAD

**Issue by joner11234** [oddfar/campus-imaotai#46]
报错如下
ERROR  |IMTServiceImpl.java:143 |「发送验证码-失败」：{"code":4010,"message":"获取验证码失败"}
 |ERROR  |SimpleAsyncUncaughtExceptionHandler.java:39 |Unexpected exception occurred invoking async method: public java.lang.Boolean com.oddfar.campus.business.service.impl.IMTServiceImpl.sendCode(java.lang.String)
com.oddfar.campus.common.exception.ServiceException: 发送验证码错误
	at com.oddfar.campus.business.service.impl.IMTServiceImpl.sendCode(IMTServiceImpl.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by joner11234** [comment]
换了其他的手机号也提示这个错误

**Comment by oddfar** [comment]
可能频繁了，等会就行。或者网络不行

**Comment by joner11234** [comment]
OK 可以在手机app上获取一个验证码，直接在网页上输入登录
